### ISSUE TITLE
Provided blocks.det to .hap code produces error

### ISSUE THREAD

**Issue by RJDan** [CAST-genomics/haptools#235]
Hello 

The code provided on your website for converting the plink output (*blocks.det) into the haps format does not parse the blocks.det file properly.

I encountered several errors in trying to run an example dataset. Can you please confirm that the code on the webpage is the current working version?

I am referring to this code: https://haptools.readthedocs.io/en/stable/api/examples.html

Thanks!

**Comment by aryarm** [comment]
Hi @RJDan,

Thank you so much for catching these bugs and reporting them! You can refer to d06d50a27b1ae847a044e9bb287ed186c58aa53f for the fixes:
```diff
    # iterate through lines of the .blocks.det file
    with open("tests/data/simple.blocks.det") as blocks_file:
-        for idx, line in enumerate(blocks_file.readlines()):
+        for idx, line in enumerate(blocks_file.read().splitlines()[1:]):
            # initialize variables and parse line from the blocks file
            hap_id = f"H{idx}"
            chrom, bp1, bp2, kb, nsnps, snps = line.split("\t")
            # create a haplotype line in the .hap file
-            hp.data[hap_id] = data.Haplotype(chrom=chrom, start=bp1, end=bp2, id=hap_id)
+            hp.data[hap_id] = data.Haplotype(chrom=chrom, start=int(bp1), end=int(bp2), id=hap_id)
            # fetch alleles from the genotypes file
            snp_gts = gt.subset(variants=tuple(snps.split("|")))
```

**Comment by aryarm** [comment]
ok, we've merged PR #236

you can view the new docs here:
https://haptools.readthedocs.io/en/latest/api/examples.html

we'll be publishing a new version of haptools with these changes soon (probably by EOD)

**Comment by aryarm** [comment]
Hi @RJDan ,

Can you confirm the fixes worked for you? I just want to double-check before moving forward with the new release.

**Comment by RJDan** [comment]
Hello Aryarm
Thanks for the quick reply. 
Unfortunately it does not resolve all the issues I am having. 
I don't code in python so I can't offer direct edits to address the issue, but I will tell you what I found from manually editing the input files.

- The python script does not correctly parse the *blocks.det file from the latest version of plink1.9. The script adds a column at the beginning of the *blocks.det file and does not recognise the delim character (white space). So I end with an error for mismatching number of columns to what is expected. When I manually replace white space with tab and remove the first (empty) column in the input, then it proceeds.
-  The script does not 'collect' all the SNP names. It seems to systematically drop one of the SNP names from the last column and gives a warning that it is proceeding  with one less variant than requested. I added a '|' to the beginning and end of the list of SNPs. This ensured that all SNPs were collected. I then get a warning that it is proceeding with two less SNPs than requested but the expected number of SNPs is correctly added to the hap file.
- The script tries to parse the header line in the *blocks.det file, giving an warning that it will proceed with no variants for that line
- The docs makes no mention if the input data (vcf) should be phased  or not.

**Comment by aryarm** [comment]
Ah! I'm sorry about all of the trouble, but thank you for providing such detailed and helpful feedback.

I thought I had resolved some of those issues, though. Are you sure that you're using the right version of the documentation? It's a bit confusing, but since we haven't released a new version of haptools yet, the "stable" docs haven't yet changed. The "latest" changes from the main branch are at a different URL:
https://haptools.readthedocs.io/en/latest/api/examples.html <-- this has the most recent changes
instead of
https://haptools.readthedocs.io/en/stable/api/examples.html

Here are my responses:

- > The python script does not correctly parse the *blocks.det file from the latest version of plink1.9. The script adds a column at the beginning of the *blocks.det file and does not recognise the delim character (white space). So I end with an error for mismatching number of columns to what is expected. When I manually replace white space with tab and remove the first (empty) column in the input, then it proceeds.

    I thought .blocks.det files were supposed to be tab-separated, and I don't think they usually have an empty column at the beginning? Perhaps this is an issue with the way that the example .blocks.det file appears when it is formatted in the old docs.
    In the new docs, I've updated the example and the formatting so that there shouldn't be an empty column. I also directly link to [the file on GitHub](https://github.com/cast-genomics/haptools/blob/main/tests/data/simple.blocks.det) so that people can download the file instead of trying to copy-paste it. Please note that I changed the contents of the example file to make it simpler, as well.
    Since you pointed this out, I'm also going to open a new PR to change the script so that it handles arbitrary white-space as well as tabs. Here's that change:

    ```diff
            for idx, line in enumerate(blocks_file.read().splitlines()[1:]):
                # initialize variables and parse line from the blocks file
                hap_id = f"H{idx}"
    +           chrom, bp1, bp2, kb, nsnps, snps = line.split("\t")
    -           chrom, bp1, bp2, kb, nsnps, snps = line.split()
    
                # create a haplotype line in the .hap file
                hp.data[hap_id] = data.Haplotype(
    ```

- > The script does not 'collect' all the SNP names. It seems to systematically drop one of the SNP names from the last column and gives a warning that it is proceeding with one less variant than requested. I added a '|' to the beginning and end of the list of SNPs. This ensured that all SNPs were collected. I then get a warning that it is proceeding with two less SNPs than requested but the expected number of SNPs is correctly added to the hap file.

    I think this should be fixed by the `splitlines()` in the first of the two changes I mentioned earlier:
    ```diff
        # iterate through lines of the .blocks.det file
        with open("input.blocks.det") as blocks_file:
    -       for idx, line in enumerate(blocks_file.readlines()):
    +       for idx, line in enumerate(blocks_file.read().splitlines()[1:]):
                # initialize variables and parse line from the blocks file
                hap_id = f"H{idx}"
    ```
    The issue was that the newline character (`\n`) was getting appended to the last SNP, so it wasn't recognizable, but `splitlines()` should automatically remove the newlines.

- > The script tries to parse the header line in the *blocks.det file, giving an warning that it will proceed with no variants for that line

    I think this should be fixed by the `[1:]` in the first of the two changes I mentioned earlier:
    ```diff
        # iterate through lines of the .blocks.det file
        with open("input.blocks.det") as blocks_file:
    -       for idx, line in enumerate(blocks_file.readlines()):
    +       for idx, line in enumerate(blocks_file.read().splitlines()[1:]):
                # initialize variables and parse line from the blocks file
                hap_id = f"H{idx}"
    ```
    The `[1:]` should remove the header line from the lines before they are parsed by the rest of the script.

- > The docs makes no mention if the input data (vcf) should be phased or not.

    Thanks for catching this! I'll also add this in the new PR.
    They should indeed be phased. Otherwise, the `transform` command would be unable to determine whether a sample has both alleles of a haplotype.

Please let me know if you run into any more issues!

**Comment by RJDan** [comment]
Hello

Sorry, I should have clarified in the post: I am now testing with another dataset, not the example data.  The output I get from plink is different from the example data, so I needed to trouble shoot for my real data.

I am still getting the following error when I use the *blocks.det file as output by plink. (I have not edited the file at all)

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
ValueError: not enough values to unpack (expected 6, got 1)
```

When I run the following on the *blocks.det file before running the python script, the error goes away.

```
sed \
-e "s/^ \+//g" \
-e "s/ \+/\t/g" \
INPUTFILE > OUTPUTFILE
```

So it seems I still need to 1) remove the leading spaces that are creating a  false column and 2) replace whitespaces with tabs.

Your edits do seem to have got rid of the other issues, though!

Thanks for all the help!

**Comment by aryarm** [comment]
huh, that's very interesting. Well, in case you continue to get any leading whitespace in your `.blocks.det` files, I've added another change to the PR to handle that, as well:
```diff
        for idx, line in enumerate(blocks_file.read().splitlines()[1:]):
            # initialize variables and parse line from the blocks file
            hap_id = f"H{idx}"
-           chrom, bp1, bp2, kb, nsnps, snps = line.split("\t")
+           chrom, bp1, bp2, kb, nsnps, snps = line.strip().split()
            # create a haplotype line in the .hap file
            hp.data[hap_id] = data.Haplotype(
```
The docs will get updated with the new changes once we merge the PR.
